FROM centos:latest
MAINTAINER Pavel Podkorytov <pod.pavel@gmail.com>

ENV USERID={USERID}
ENV GROUPID={GROUPID}

# Install main dependencies
RUN yum install -y epel-release rpmdevtools make yum-utils && \
    yum clean all
# Install more dependencies for project here

# Create builder group and user
RUN groupadd -g $GROUPID builder && \
    useradd -m -s /bin/bash -u $USERID -g $GROUPID builder

USER builder
RUN mkdir -p ~/rpmbuild
WORKDIR /home/builder/rpmbuild
